# Generated by Django 6.0 on 2025-12-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=20)),
                ('huespedes', models.IntegerField()),
                ('camas', models.CharField(max_length=9)),
                ('fecha_entrada', models.DateField(verbose_name='fecha de entrada: ')),
                ('fecha_salida', models.DateField(verbose_name='fecha de salida: ')),
            ],
        ),
    ]
