# Generated by Django 6.0 on 2025-12-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='camas',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='correo',
            field=models.EmailField(max_length=100),
        ),
    ]
