# Generated by Django 6.0 on 2025-12-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto_noticia', models.CharField(max_length=100000)),
                ('fecha', models.DateTimeField(verbose_name='fecha de publicacion: ')),
            ],
        ),
    ]
